# valid registration - should work, but only once because email is unique
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123",
    "role": "student"
}

###

# valid credentials once user registered - should work
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password123"
}

###

# invalid credentials - should fail
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jerry.black@yahoo.com",
    "password": "password789"
}

###

# make a user a manager
PUT http://localhost:3000/auth/make-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbInN0dWRlbnQiLCJtYW5hZ2VyIl0sImlhdCI6MTY4NjM0MzY3Nn0.jh_bogLMCZ7KViqv2w9YWPGTc72tWTZzAG8YdMe0LI4
Content-Type: application/json

{
    "name": "Jerry Black",
    "email": "jerry.black@example.com",
    "password": "password789"
}

###

# remove a role from a user
PUT http://localhost:3000/auth/remove-role/9/manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbInN0dWRlbnQiLCJtYW5hZ2VyIl0sImlhdCI6MTY4NjM0MzY3Nn0.jh_bogLMCZ7KViqv2w9YWPGTc72tWTZzAG8YdMe0LI4

###

# delete a user
DELETE http://localhost:3000/auth/delete-user/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbInN0dWRlbnQiLCJtYW5hZ2VyIl0sImlhdCI6MTY4NjM0MzY3Nn0.jh_bogLMCZ7KViqv2w9YWPGTc72tWTZzAG8YdMe0LI4

